#!/bin/sh

# add PREEMPT config

for i in kernel-*.config
do
cat << EOF >> $i
## for tkg
CONFIG_SCHED_ALT=y
CONFIG_SCHED_BMQ=y
# CONFIG_SCHED_PDS is not set
# CONFIG_HZ_750 is not set
CONFIG_WINESYNC=y
CONFIG_ZENIFY=y
CONFIG_USER_NS_UNPRIVILEGED=y
# CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3 is not set
# CONFIG_LRU_GEN is not set
## for march
# CONFIG_MK8SSE3 is not set
# CONFIG_MK10 is not set
# CONFIG_MBARCELONA is not set
# CONFIG_MBOBCAT is not set
# CONFIG_MJAGUAR is not set
# CONFIG_MBULLDOZER is not set
# CONFIG_MPILEDRIVER is not set
# CONFIG_MSTEAMROLLER is not set
# CONFIG_MEXCAVATOR is not set
# CONFIG_MZEN is not set
# CONFIG_MZEN2 is not set
# CONFIG_MZEN3 is not set
# CONFIG_MNEHALEM is not set
# CONFIG_MWESTMERE is not set
# CONFIG_MSILVERMONT is not set
# CONFIG_MGOLDMONT is not set
# CONFIG_MGOLDMONTPLUS is not set
# CONFIG_MSANDYBRIDGE is not set
# CONFIG_MIVYBRIDGE is not set
# CONFIG_MHASWELL is not set
# CONFIG_MBROADWELL is not set
# CONFIG_MSKYLAKE is not set
# CONFIG_MSKYLAKEX is not set
# CONFIG_MCANNONLAKE is not set
# CONFIG_MICELAKE is not set
# CONFIG_MCASCADELAKE is not set
# CONFIG_MCOOPERLAKE is not set
# CONFIG_MTIGERLAKE is not set
# CONFIG_MSAPPHIRERAPIDS is not set
# CONFIG_MROCKETLAKE is not set
# CONFIG_MALDERLAKE is not set
# CONFIG_MNATIVE_INTEL is not set
# CONFIG_MNATIVE_AMD is not set
# CONFIG_GENERIC_CPU2 is not set
# CONFIG_GENERIC_CPU3 is not set
# CONFIG_GENERIC_CPU4 is not set
CONFIG_PMIC_OPREGION=y
CONFIG_BYTCRC_PMIC_OPREGION=y
CONFIG_I2C_DESIGNWARE_CORE=y
CONFIG_I2C_DESIGNWARE_PLATFORM=y
CONFIG_I2C_DESIGNWARE_BAYTRAIL=y
CONFIG_I2C_DESIGNWARE_PCI=y
CONFIG_GPIO_CRYSTAL_COVE=y
CONFIG_INTEL_SOC_PMIC=y
CONFIG_MEDIA_SUPPORT=m
CONFIG_MEDIA_SUPPORT_FILTER=y
CONFIG_VIDEO_ADV_DEBUG=y
CONFIG_STAGING=y
CONFIG_STAGING_MEDIA=y
CONFIG_INTEL_ATOMISP=y
CONFIG_VIDEO_ATOMISP=m
CONFIG_VIDEO_ATOMISP_MSRLIST_HELPER=m
CONFIG_VIDEO_ATOMISP_MT9M114=m
CONFIG_INTEL_ATOMISP2_LED
CONFIG_V4L2_CCI
CONFIG_V4L2_CCI_I2C
CONFIG_INTEL_ATOMISP2_PDX86
CONFIG_PWM_LPSS_PCI
CONFIG_IPU_BRIDGE
CONFIG_INTEL_VSC
CONFIG_VIDEO_ATOMISP_GC0310=n
CONFIG_VIDEO_ATOMISP_OV2680=n
CONFIG_VIDEO_ATOMISP_OV5693=n
CONFIG_VIDEO_ATOMISP_LM3554=n
EOF

sed -e "s/CONFIG_CRYPTO_XXHASH=.$/CONFIG_CRYPTO_XXHASH=y/g" $i > $i.tmp
mv $i.tmp $i
sed -e "s/CONFIG_CRYPTO_BLAKE2B=.$/CONFIG_CRYPTO_BLAKE2B=y/g" $i > $i.tmp
mv $i.tmp $i
done
