name: Build kernel

on:
  push:
    branches: [ main ]

env:
  COPR_CONFIG_FILE: ${{ github.workspace }}/copr

jobs:
  feodora-kernel-build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Copr config
        run: |
          touch $COPR_CONFIG_FILE
          chmod 600 $COPR_CONFIG_FILE
          envsubst < ${{ github.workspace }}/build-script/copr-config.template > $COPR_CONFIG_FILE
        env:
          COPR_LOGIN: ${{ secrets.COPR_LOGIN }}
          COPR_USERNAME: ${{ secrets.COPR_USERNAME }}
          COPR_TOKEN: ${{ secrets.COPR_TOKEN }}
          COPR_URL: ${{ secrets.COPR_URL }}

      - name: Run kernel-mock.sh in docker
        uses: addnab/docker-run-action@v3
        with:
          image: fedora:latest
          options: -v ${{ github.workspace }}:/build --privileged
          run: |
            echo "Install packages"
            dnf -y install koji copr-cli mock
            echo "Run script"
            cd /build/build-script
            ./kernel-mock.sh -c -f /build/copr
      
      - name: Remove Copr config
        run: rm -f $COPR_CONFIG_FILE

      - name: Archive .src.rpm artifacts
        uses: actions/upload-artifact@v3
        with:
          name: source rpm
          path: |
            results/*.src.rpm

      - name: Archive .log artifacts
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: |
            results/*.log