name: Build kernel

on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - env:
        COPR_CONFIG_FILE: /tmp/copr

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Copr config
        run: |
          touch $COPR_CONFIG_FILE
          chmod 600 $COPR_CONFIG_FILE
          envsubst < copr-config.template > $COPR_CONFIG_FILE
        env:
          COPR_LOGIN: ${{ secrets.COPR_LOGIN }}
          COPR_USERNAME: ${{ secrets.COPR_USERNAME }}
          COPR_TOKEN: ${{ secrets.COPR_TOKEN }}
          COPR_URL: ${{ secrets.COPR_URL }}

      - name: Run kernel-mock.sh in docker
        uses: addnab/docker-run-action@v3
        with:
          image: fedora:latest
          options: -v ${{ github.workspace }}:/build --privileged
          run: |
            echo "Install packages"
            dnf -y install koji copr-cli mock
            echo "Run script"
            cd /build/build-script
            ./kernel-mock.sh -c -f $COPR_CONFIG_FILE
      
      - name: Remove Copr config
        run: rm -f $COPR_CONFIG_FILE

      - name: Check results
        run: |
            ls -l ${{ github.workspace }}/results
            find ${{ github.workspace }} -name "*.log" -ls -exec cat {} \;